name: Crear y subir imagen Docker

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen
        run: docker build -t dccp/ejemploimagenactionsauto:latest .

      - name: Subir imagen a Docker Hub
        run: docker push dccp/ejemploimagenactionsauto:latest