name: Crear y subir imagen Docker
on: 
  workflow_dispatch

jobs:
  publish_images: 
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: checkout
        uses: actions/checkout@v4
      - name: construir imagen
        run: docker build -t dccp/ejemplo-imagen-actions:latest .
      - name: subir imagen a dockerhub
        run: docker push dccp/ejemplo-imagen-actions:latest